name: Deploy
type: module
description: ' Allows content to be deployed between servers. Either to be used as a content staging solution or to deploy content across a cluster of different sites.'
# core: 8.x
dependencies:
  - workspace:workspace

# Information added by Drupal.org packaging script on 2018-11-12
version: '8.x-1.0-beta13'
core: '8.x'
project: 'deploy'
datestamp: 1542015498
